/**
 * This is the default plugin for Lynx docs's customization of TypeDoc.
 * @see https://typedoc-plugin-markdown.org/api-docs/Document.Customizing-Output
 *
 * Instead of writing it as a "real plugin" which requires a build step or
 * writing it in untyped `.mjs`, we simply extends upon `app` directly.
 */

import * as fs from 'node:fs';
import * as path from 'node:path';
import {
  type MarkdownApplication,
  MarkdownPageEvent,
} from 'typedoc-plugin-markdown';

const DUMP_NAVIGATION_JSON = false;

/**
 * Customize the TypeDoc application.
 * @param app - The TypeDoc application.
 * @see https://typedoc-plugin-markdown.org/api-docs/Document.Customizing-Output
 */
export function customize(app: MarkdownApplication, outputDir: string) {
  // Write global prologue to all pages.
  app.renderer.on(MarkdownPageEvent.BEGIN, (page) => {
    page.contents = `${PROLOGUE}\n\n${page.contents}`;
  });

  // Dump navigation.json to a file.
  // This is currently not used but left here to show this functionality.
  if (DUMP_NAVIGATION_JSON) {
    app.renderer.postRenderAsyncJobs.push(async (renderer) => {
      // The navigation JSON structure is available on the navigation object.
      const navigation = renderer.navigation;

      // This can be parsed to something else or written straight to a file:
      fs.writeFileSync(
        path.join(outputDir, 'navigation.json'),
        JSON.stringify(navigation),
      );
    });
  }
}

const PROLOGUE = `{/*
* This file is generated by @lynx-js/tool-typedoc.
* Do not edit this file directly.
* @generated
*/}

{/* Import all components as Lynx to allow dynamic lookup in TSDoc writings. */}
import * as Lynx from '@lynx';
`;
