#!/usr/bin/env python3
# Copyright 2026 The Lynx Authors. All rights reserved.
# Licensed under the Apache License Version 2.0 that can be found in the
# LICENSE file in the root directory of this source tree.

"""Update or check generated Lynx DevTool CDP website docs."""

from __future__ import annotations

import argparse
import difflib
import json
import re
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Callable, Iterable

try:
    import yaml
except ImportError as exc:
    raise SystemExit(
        "error: PyYAML is required. Install it with: python3 -m pip install PyYAML"
    ) from exc


BEGIN_MARKER = "{/* BEGIN GENERATED CDP REFERENCE */}"
END_MARKER = "{/* END GENERATED CDP REFERENCE */}"
LEGACY_BEGIN_MARKER = "<!-- BEGIN GENERATED CDP REFERENCE -->"
LEGACY_END_MARKER = "<!-- END GENERATED CDP REFERENCE -->"
GENERATOR_PATH = "packages/lynx-cdp/generate_cdp_docs.py"
GENERATOR_COMMENT = (
    f"Generated by {GENERATOR_PATH}. Do not edit this block by hand."
)
PLACEHOLDER_SUMMARY_PREFIX = "Initial documentation entry"
CUSTOM_ORIGIN = "lynx-extension"
VALID_ORIGINS = frozenset({"standard", CUSTOM_ORIGIN})
VALID_SCOPES = frozenset({"global", "instance", "global-and-instance"})


@dataclass(frozen=True)
class Method:
    domain: str
    name: str
    origin: str
    source: str

    @property
    def key(self) -> str:
        return f"{self.domain}.{self.name}"


@dataclass(frozen=True)
class Domain:
    name: str
    origin: str
    scope: str
    methods: tuple[Method, ...]


@dataclass(frozen=True)
class V8Reference:
    display_name: str
    cdp_root: str


@dataclass(frozen=True)
class Manifest:
    upstream_root: str
    v8_reference: V8Reference
    domains: tuple[Domain, ...]

    @property
    def method_keys(self) -> set[tuple[str, str]]:
        return {
            (method.domain, method.name)
            for domain in self.domains
            for method in domain.methods
        }

    @property
    def methods(self) -> tuple[Method, ...]:
        return tuple(method for domain in self.domains for method in domain.methods)


class DocsError(Exception):
    pass


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Update or check generated Lynx DevTool CDP website docs."
    )
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true", help="rewrite the MDX output")
    mode.add_argument("--check", action="store_true", help="check the MDX output")
    parser.add_argument(
        "--output-path",
        required=True,
        type=Path,
        help="extensionless output base path, such as docs/en/api/cdp/api-ref",
    )
    parser.add_argument(
        "--manifest",
        required=True,
        type=Path,
        help="path to the generated CDP manifest from the Lynx source repository",
    )
    parser.add_argument(
        "--custom-docs",
        required=True,
        type=Path,
        help="path to the custom CDP docs directory from the Lynx source repository",
    )

    args = parser.parse_args()
    manifest_path = args.manifest.resolve()
    custom_docs_dir = args.custom_docs.resolve()

    try:
        output_path = args.output_path.resolve()
        if output_path.suffix:
            raise DocsError("--output-path must not include a file extension")
        manifest = load_manifest(manifest_path)
        custom_docs = load_custom_docs(custom_docs_dir, manifest)
        expected_outputs = build_expected_outputs(
            output_path, manifest, custom_docs
        )

        if args.write:
            write_outputs(expected_outputs, output_path)
            return 0

        return check_outputs(
            expected_outputs, output_path, manifest_path, custom_docs_dir
        )
    except DocsError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1


def load_manifest(path: Path) -> Manifest:
    data = load_yaml_mapping(path)
    version = data.get("version")
    if version != 2:
        raise DocsError(f"{path} must contain version: 2")
    upstream_root = require_string(data, "upstreamRoot", path)
    external_references = require_mapping(data, "externalReferences", path)
    v8_data = require_mapping(external_references, "v8", path)
    v8_reference = V8Reference(
        display_name=require_string(v8_data, "displayName", path),
        cdp_root=require_string(v8_data, "cdpRoot", path).rstrip("/"),
    )
    domains_data = require_list(data, "domains", path)

    domains: list[Domain] = []
    for domain_data in domains_data:
        if not isinstance(domain_data, dict):
            raise DocsError(f"{path} domains entries must be mappings")
        domain_name = require_string(domain_data, "name", path)
        domain_origin = require_string(domain_data, "origin", path)
        domain_scope = require_string(domain_data, "scope", path)
        if domain_origin not in VALID_ORIGINS:
            raise DocsError(f"{path} has invalid origin for {domain_name}: {domain_origin}")
        if domain_scope not in VALID_SCOPES:
            raise DocsError(f"{path} has invalid scope for {domain_name}: {domain_scope}")
        methods_data = require_list(domain_data, "methods", path)
        methods: list[Method] = []
        for method_data in methods_data:
            if not isinstance(method_data, dict):
                raise DocsError(f"{path} method entries must be mappings")
            method_name = require_string(method_data, "name", path)
            method_origin = require_string(method_data, "origin", path)
            source = require_string(method_data, "source", path)
            if method_origin not in VALID_ORIGINS:
                raise DocsError(
                    f"{path} has invalid origin for {domain_name}.{method_name}: "
                    f"{method_origin}"
                )
            methods.append(
                Method(
                    domain=domain_name,
                    name=method_name,
                    origin=method_origin,
                    source=source,
                )
            )
        domains.append(
            Domain(
                name=domain_name,
                origin=domain_origin,
                scope=domain_scope,
                methods=tuple(methods),
            )
        )

    return Manifest(
        upstream_root=upstream_root.rstrip("/"),
        v8_reference=v8_reference,
        domains=tuple(domains),
    )


def load_custom_docs(
    custom_docs_dir: Path, manifest: Manifest
) -> dict[tuple[str, str], dict[str, Any]]:
    custom_docs: dict[tuple[str, str], dict[str, Any]] = {}
    if not custom_docs_dir.exists():
        raise DocsError(f"missing custom CDP docs directory: {custom_docs_dir}")

    known_methods = manifest.method_keys
    for doc_file in sorted(custom_docs_dir.glob("*/methods/*.yaml")):
        domain = doc_file.parents[1].name
        method = doc_file.stem
        key = (domain, method)
        if key not in known_methods:
            raise DocsError(f"custom CDP docs without matching metadata method: {doc_file}")
        doc = load_yaml_mapping(doc_file)
        validate_custom_doc(doc_file, doc)
        custom_docs[key] = doc

    missing_docs = []
    for method in manifest.methods:
        if method.origin == CUSTOM_ORIGIN and (method.domain, method.name) not in custom_docs:
            missing_docs.append(
                custom_docs_dir / method.domain / "methods" / f"{method.name}.yaml"
            )
    if missing_docs:
        raise DocsError(
            "missing custom CDP docs:\n  "
            + "\n  ".join(str(path) for path in missing_docs)
        )

    return custom_docs


def load_yaml_mapping(path: Path) -> dict[str, Any]:
    if not path.exists():
        raise DocsError(f"missing file: {path}")
    try:
        data = yaml.safe_load(path.read_text(encoding="utf-8"))
    except yaml.YAMLError as exc:
        raise DocsError(f"invalid YAML in {path}: {exc}") from exc
    if not isinstance(data, dict):
        raise DocsError(f"{path} must contain a YAML mapping")
    return data


def validate_custom_doc(path: Path, doc: dict[str, Any]) -> None:
    require_string(doc, "summary", path)
    validate_named_field_list(path, doc, "parameters")
    validate_named_field_list(path, doc, "returns")
    validate_events(path, doc)
    validate_string_list(path, doc, "notes")
    examples = doc.get("examples")
    if examples is None:
        return
    if not isinstance(examples, list):
        raise DocsError(f"{path} examples must be a list")
    for index, example in enumerate(examples):
        if not isinstance(example, dict):
            raise DocsError(f"{path} examples[{index}] must be a mapping")
        require_string(example, "title", path)
        request = example.get("request")
        response = example.get("response")
        if request is not None and not isinstance(request, dict):
            raise DocsError(f"{path} examples[{index}].request must be a mapping")
        if response is not None and not isinstance(response, dict):
            raise DocsError(f"{path} examples[{index}].response must be a mapping")


def validate_named_field_list(path: Path, doc: dict[str, Any], key: str) -> None:
    value = doc.get(key)
    if value is None:
        return
    if not isinstance(value, list):
        raise DocsError(f"{path} {key} must be a list")
    for index, item in enumerate(value):
        if not isinstance(item, dict):
            raise DocsError(f"{path} {key}[{index}] must be a mapping")
        require_string(item, "name", path)
        require_string(item, "type", path)
        description = item.get("description")
        if description is not None and not isinstance(description, str):
            raise DocsError(f"{path} {key}[{index}].description must be a string")


def validate_events(path: Path, doc: dict[str, Any]) -> None:
    events = doc.get("events")
    if events is None:
        return
    if not isinstance(events, list):
        raise DocsError(f"{path} events must be a list")
    for index, event in enumerate(events):
        # TODO: Migrate string events in Lynx custom_cdp_docs to name/description
        # mappings, then remove string support here and in render_events.
        # Update schema docs and tests after the migrated metadata is available.
        if isinstance(event, str):
            continue
        if not isinstance(event, dict):
            raise DocsError(f"{path} events[{index}] must be a mapping or a string")
        name = event.get("name")
        if not isinstance(name, str) or not name.strip():
            raise DocsError(f"{path} events[{index}].name must be a non-empty string")
        if "description" in event and not isinstance(event["description"], str):
            raise DocsError(f"{path} events[{index}].description must be a string")


def validate_string_list(path: Path, doc: dict[str, Any], key: str) -> None:
    value = doc.get(key)
    if value is None:
        return
    if not isinstance(value, list):
        raise DocsError(f"{path} {key} must be a list")
    for index, item in enumerate(value):
        if not isinstance(item, str):
            raise DocsError(f"{path} {key}[{index}] must be a string")


def build_expected_outputs(
    output_path: Path,
    manifest: Manifest,
    custom_docs: dict[tuple[str, str], dict[str, Any]],
) -> dict[Path, str]:
    summary_path = output_path.with_suffix(".mdx")
    domain_dir = output_path
    domains = ordered_domains(manifest.domains)
    domain_paths = {
        domain_dir / f"{domain_filename(domain.name)}.mdx" for domain in domains
    }
    if len(domain_paths) != len(domains) or summary_path in domain_paths:
        raise DocsError("CDP domain names produce conflicting output file names")

    expected_outputs = {
        summary_path: build_expected_output(
            summary_path,
            render_summary_block(manifest, domain_dir.name),
            default_summary_page,
        ),
        domain_dir / "_meta.json": render_domain_meta(domains),
    }
    for domain in domains:
        output_path = domain_dir / f"{domain_filename(domain.name)}.mdx"
        expected_outputs[output_path] = build_expected_domain_output(
            output_path,
            domain,
            render_domain_block(manifest.upstream_root, domain, custom_docs),
        )
    return expected_outputs


def build_expected_domain_output(
    output_path: Path, domain: Domain, generated_block: str
) -> str:
    expected = build_expected_output(
        output_path,
        generated_block,
        lambda block: default_domain_page(domain, block),
    )
    old_title = f"# {domain.name} CDP API Reference\n"
    return expected.replace(old_title, f"# {domain.name}\n", 1)


def write_outputs(expected_outputs: dict[Path, str], domain_dir: Path) -> None:
    stale_domain_pages = find_stale_domain_pages(domain_dir, expected_outputs)
    for path, expected in expected_outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(expected, encoding="utf-8")
        print(f"Updated {path}")
    for path in stale_domain_pages:
        path.unlink()
        print(f"Removed {path}")


def build_expected_output(
    output_path: Path,
    generated_block: str,
    default_output: Callable[[str], str],
) -> str:
    if not output_path.exists():
        return default_output(generated_block)
    current = output_path.read_text(encoding="utf-8")
    begin_marker = BEGIN_MARKER
    end_marker = END_MARKER
    if BEGIN_MARKER not in current or END_MARKER not in current:
        begin_marker = LEGACY_BEGIN_MARKER
        end_marker = LEGACY_END_MARKER
    if begin_marker not in current or end_marker not in current:
        raise DocsError(
            f"{output_path} must contain both {BEGIN_MARKER} and {END_MARKER}"
        )
    before, rest = current.split(begin_marker, 1)
    _, after = rest.split(end_marker, 1)
    return f"{before}{BEGIN_MARKER}\n{generated_block}\n{END_MARKER}{after}"


def default_summary_page(generated_block: str) -> str:
    return (
        "# CDP API Reference\n\n"
        "This page lists the Chrome DevTools Protocol methods supported by Lynx "
        "DevTool. Standard CDP methods link to the Chrome DevTools Protocol "
        "reference. Lynx extensions are documented from the Lynx source "
        "metadata.\n\n"
        f"{BEGIN_MARKER}\n"
        f"{generated_block}\n"
        f"{END_MARKER}\n"
    )


def default_domain_page(domain: Domain, generated_block: str) -> str:
    return (
        f"# {domain.name}\n\n"
        f"This page documents the `{domain.name}` CDP domain supported by Lynx "
        "DevTool.\n\n"
        f"{BEGIN_MARKER}\n"
        f"{generated_block}\n"
        f"{END_MARKER}\n"
    )


def check_outputs(
    expected_outputs: dict[Path, str],
    summary_path: Path,
    manifest_path: Path,
    custom_docs_dir: Path,
) -> int:
    has_errors = False
    for output_path, expected in expected_outputs.items():
        has_errors = check_output(output_path, expected) or has_errors
    for path in find_stale_domain_pages(summary_path, expected_outputs):
        print(f"CDP docs output is stale: {path} is no longer generated.", file=sys.stderr)
        has_errors = True
    if has_errors:
        print_write_command(summary_path, manifest_path, custom_docs_dir)
        return 1
    return 0


def check_output(output_path: Path, expected: str) -> bool:
    if not output_path.exists():
        print(f"CDP docs output is missing: {output_path}", file=sys.stderr)
        return True
    actual = output_path.read_text(encoding="utf-8")
    if actual == expected:
        return False

    print(f"CDP docs output is stale: {output_path}", file=sys.stderr)
    print(file=sys.stderr)
    for line in difflib.unified_diff(
        actual.splitlines(),
        expected.splitlines(),
        fromfile=str(output_path),
        tofile=f"{output_path} (expected)",
        lineterm="",
    ):
        print(line, file=sys.stderr)
    return True


def find_stale_domain_pages(
    domain_dir: Path, expected_outputs: dict[Path, str]
) -> list[Path]:
    if not domain_dir.exists():
        return []
    return [
        path
        for path in sorted(domain_dir.glob("*.mdx"))
        if path not in expected_outputs and is_generated_domain_page(path)
    ]


def is_generated_domain_page(path: Path) -> bool:
    contents = path.read_text(encoding="utf-8")
    return (
        GENERATOR_COMMENT in contents
        and BEGIN_MARKER in contents
        and END_MARKER in contents
    )


def print_write_command(
    output_path: Path, manifest_path: Path, custom_docs_dir: Path
) -> None:
    print("Run:", file=sys.stderr)
    print(
        f"  python3 {GENERATOR_PATH} --write"
        f" --manifest {manifest_path}"
        f" --custom-docs {custom_docs_dir}"
        f" --output-path {output_path}",
        file=sys.stderr,
    )


def render_summary_block(manifest: Manifest, domain_dir_name: str) -> str:
    lines: list[str] = [
        f"{{/* {GENERATOR_COMMENT} */}}",
        "",
        *render_experimental_notice(),
        "## JavaScript Runtime Support",
        "",
        "The runtime-domain methods in this reference are implemented by the "
        "PrimJS inspector. PrimJS is used for both Main-Thread Scripting (MTS) "
        "and Background-Thread Scripting (BTS).",
        "",
        f"{manifest.v8_reference.display_name}-backed debugging is delegated to "
        f"{manifest.v8_reference.display_name} Inspector. Refer to the "
        f"{link(f'{manifest.v8_reference.display_name} CDP reference', manifest.v8_reference.cdp_root)} "
        "for the V8 Inspector protocol version adopted by Lynx. V8 methods are "
        "not listed individually in this reference.",
        "",
        "## Summary",
        "",
    ]

    standard_count = sum(1 for method in manifest.methods if method.origin == "standard")
    extension_count = sum(
        1 for method in manifest.methods if method.origin == CUSTOM_ORIGIN
    )
    lines.extend(
        render_table(
            ["Category", "Count"],
            [
                ["Standard CDP methods", str(standard_count)],
                ["Lynx extensions", str(extension_count)],
            ],
            right_aligned={1},
        )
    )
    lines.extend(["", "## Domain Overview", ""])
    domain_rows = []
    for domain in ordered_domains(manifest.domains):
        origin_counts = count_methods_by_origin(domain.methods)
        domain_name = link(
            domain.name, f"./{domain_dir_name}/{domain_filename(domain.name)}"
        )
        domain_rows.append(
            [
                domain_name,
                code(domain.scope),
                str(origin_counts["standard"]),
                str(origin_counts[CUSTOM_ORIGIN]),
            ]
        )
    lines.extend(
        render_table(
            ["Domain", "Scope", "Standard", "Lynx extensions"],
            domain_rows,
            right_aligned={2, 3},
        )
    )

    return "\n".join(lines).rstrip() + "\n"


def render_experimental_notice() -> list[str]:
    return [
        ":::warning Experimental reference",
        "This generated reference is still being completed.",
        "",
        "- CDP events are not included yet.",
        "- Some Lynx extensions are listed but do not yet have detailed documentation.",
        "- Method descriptions are not automatically verified against the "
        "implementation and may be incomplete or inaccurate.",
        "",
        "Verify behavior against the implementation and the linked upstream CDP "
        "reference before relying on it.",
        ":::",
        "",
    ]


def render_domain_meta(domains: Iterable[Domain]) -> str:
    entries = [
        {
            "type": "file",
            "name": domain_filename(domain.name),
            "label": domain.name,
        }
        for domain in domains
    ]
    return json.dumps(entries, indent=2) + "\n"


def render_domain_block(
    upstream_root: str,
    domain: Domain,
    custom_docs: dict[tuple[str, str], dict[str, Any]],
) -> str:
    methods = documented_methods(domain.methods, custom_docs)
    lines: list[str] = [
        f"{{/* {GENERATOR_COMMENT} */}}",
        "",
        *render_experimental_notice(),
        "## Overview",
        "",
    ]
    lines.append(f"- Scope: {code(domain.scope)}")
    if domain.origin == "standard":
        lines.append(f"- CDP domain: {link(domain.name, domain_url(upstream_root, domain.name))}")
    else:
        lines.append("- CDP domain: Lynx-specific")
    lines.append("")

    standard_methods = [method for method in methods if method.origin == "standard"]
    if standard_methods:
        lines.extend(["## Standard Methods", ""])
        for method in standard_methods:
            lines.append(
                f"- {link(method.key, method_url(upstream_root, method.domain, method.name))}"
            )
        lines.append("")

    custom_methods = [method for method in methods if method.origin == CUSTOM_ORIGIN]
    if custom_methods:
        lines.extend(["## Lynx Extensions", ""])
        for method in custom_methods:
            doc = custom_docs[(method.domain, method.name)]
            lines.extend(render_custom_method(method, doc, heading_level="###"))

    if not standard_methods and not custom_methods:
        lines.extend(
            [
                "## Documentation Status",
                "",
                "Detailed documentation for this domain is being prepared.",
                "",
            ]
        )

    return "\n".join(lines).rstrip() + "\n"


def documented_methods(
    methods: Iterable[Method], custom_docs: dict[tuple[str, str], dict[str, Any]]
) -> tuple[Method, ...]:
    return tuple(
        method
        for method in methods
        if method.origin != CUSTOM_ORIGIN
        or not is_placeholder_doc(custom_docs[(method.domain, method.name)])
    )


def is_placeholder_doc(doc: dict[str, Any]) -> bool:
    return str(doc["summary"]).startswith(PLACEHOLDER_SUMMARY_PREFIX)


def render_custom_method(
    method: Method, doc: dict[str, Any], *, heading_level: str
) -> list[str]:
    lines = [f"{heading_level} {code(method.key)}", ""]
    lines.append(str(doc["summary"]))
    lines.extend(["", f"- Origin: {code(method.origin)}", f"- Source: {code(method.source)}", ""])

    lines.extend(render_fields("Parameters", doc.get("parameters"), include_required=True))
    lines.extend(render_fields("Returns", doc.get("returns"), include_required=False))
    lines.extend(render_events(doc.get("events")))
    lines.extend(render_list_section("Notes", doc.get("notes")))
    lines.extend(render_examples(doc.get("examples")))
    return lines


def render_fields(
    title: str, fields: Any, *, include_required: bool
) -> list[str]:
    lines = [f"###### {title}", ""]
    if not fields:
        none_text = "No parameters." if title == "Parameters" else "No return fields."
        lines.extend([none_text, ""])
        return lines

    if include_required:
        headers = ["Name", "Type", "Required", "Description"]
    else:
        headers = ["Name", "Type", "Description"]

    rows = []
    for field in fields:
        name = table_text(code(str(field["name"])))
        field_type = table_text(code(format_type(field)))
        description = table_text(format_description(field))
        if include_required:
            required = "No" if field.get("optional") is True else "Yes"
            rows.append([name, field_type, required, description])
        else:
            rows.append([name, field_type, description])
    lines.extend(render_table(headers, rows))
    lines.append("")
    return lines


def render_events(events: Any) -> list[str]:
    values = []
    for event in events or []:
        if isinstance(event, str):
            values.append(event)
            continue
        text = code(event["name"])
        if event.get("description"):
            text += f": {event['description']}"
        values.append(text)
    return render_list_section("Events", values)


def render_list_section(title: str, values: Any) -> list[str]:
    if not values:
        return []
    lines = [f"###### {title}", ""]
    for item in values:
        lines.append(f"- {item}")
    lines.append("")
    return lines


def render_examples(examples: Any) -> list[str]:
    if not examples:
        return []
    lines = ["###### Examples", ""]
    for example in examples:
        lines.append(f"**{example['title']}**")
        lines.append("")
        if "request" in example:
            lines.extend(["Request:", "", "```json"])
            lines.append(format_json(example["request"]))
            lines.extend(["```", ""])
        if "response" in example:
            lines.extend(["Response:", "", "```json"])
            lines.append(format_json(example["response"]))
            lines.extend(["```", ""])
    return lines


def format_json(value: Any, indent: int = 0) -> str:
    prefix = " " * indent
    if isinstance(value, dict):
        if not value:
            return prefix + "{}"
        lines = [prefix + "{"]
        items = list(value.items())
        for index, (key, nested_value) in enumerate(items):
            nested = format_json(nested_value, indent + 2)
            nested_lines = nested.splitlines()
            lines.append(
                " " * (indent + 2)
                + json.dumps(str(key))
                + ": "
                + nested_lines[0].lstrip()
            )
            lines.extend(nested_lines[1:])
            if index < len(items) - 1:
                lines[-1] += ","
        lines.append(prefix + "}")
        return "\n".join(lines)

    if isinstance(value, list):
        if all(isinstance(item, (str, int, float, bool)) or item is None for item in value):
            return prefix + json.dumps(value)
        if not value:
            return prefix + "[]"
        lines = [prefix + "["]
        for index, item in enumerate(value):
            nested_lines = format_json(item, indent + 2).splitlines()
            lines.extend(nested_lines)
            if index < len(value) - 1:
                lines[-1] += ","
        lines.append(prefix + "]")
        return "\n".join(lines)

    return prefix + json.dumps(value)


def count_methods_by_origin(methods: Iterable[Method]) -> dict[str, int]:
    counts = {"standard": 0, CUSTOM_ORIGIN: 0}
    for method in methods:
        counts[method.origin] += 1
    return counts


def render_table(
    headers: list[str], rows: list[list[str]], *, right_aligned: set[int] | None = None
) -> list[str]:
    right_aligned = right_aligned or set()
    widths = [
        max(len(row[index]) for row in [headers, *rows])
        for index in range(len(headers))
    ]

    def format_row(row: list[str]) -> str:
        cells = [
            row[index].rjust(width) if index in right_aligned else row[index].ljust(width)
            for index, width in enumerate(widths)
        ]
        return "| " + " | ".join(cells) + " |"

    separator = [
        "-" * (width - 1) + ":" if index in right_aligned else "-" * width
        for index, width in enumerate(widths)
    ]
    return [format_row(headers), format_row(separator), *(format_row(row) for row in rows)]


def format_type(field: dict[str, Any]) -> str:
    field_type = str(field["type"])
    enum_values = field.get("enum")
    if isinstance(enum_values, list) and enum_values:
        field_type += " (" + " | ".join(str(value) for value in enum_values) + ")"
    return field_type


def format_description(field: dict[str, Any]) -> str:
    parts = [str(field.get("description", ""))]
    constraints = []
    if "minimum" in field:
        constraints.append(f"minimum {field['minimum']}")
    if "maximum" in field:
        constraints.append(f"maximum {field['maximum']}")
    if constraints:
        parts.append("Constraints: " + ", ".join(constraints) + ".")
    return " ".join(part for part in parts if part)


def require_string(data: dict[str, Any], key: str, path: Path) -> str:
    value = data.get(key)
    if not isinstance(value, str) or not value:
        raise DocsError(f"{path} must contain string field {key}")
    return value


def require_mapping(data: dict[str, Any], key: str, path: Path) -> dict[str, Any]:
    value = data.get(key)
    if not isinstance(value, dict):
        raise DocsError(f"{path} must contain mapping field {key}")
    return value


def require_list(data: dict[str, Any], key: str, path: Path) -> list[Any]:
    value = data.get(key)
    if not isinstance(value, list):
        raise DocsError(f"{path} must contain list field {key}")
    return value


def domain_filename(domain: str) -> str:
    words = re.sub(
        r"(?<=[a-z0-9])(?=[A-Z])|(?<=[A-Z])(?=[A-Z][a-z])",
        "-",
        domain,
    )
    return words.lower()


def ordered_domains(domains: Iterable[Domain]) -> tuple[Domain, ...]:
    return tuple(sorted(domains, key=lambda domain: domain_filename(domain.name)))


def method_url(upstream_root: str, domain: str, method: str) -> str:
    return f"{domain_url(upstream_root, domain)}#method-{method}"


def domain_url(upstream_root: str, domain: str) -> str:
    return f"{upstream_root}/{domain}/"


def link(text: str, url: str) -> str:
    return f"[{escape_link_text(text)}]({url})"


def code(text: str) -> str:
    return "`" + text.replace("`", "\\`") + "`"


def escape_link_text(text: str) -> str:
    return text.replace("[", "\\[").replace("]", "\\]")


def table_text(text: str) -> str:
    return text.replace("\n", " ").replace("|", "\\|")


if __name__ == "__main__":
    sys.exit(main())
